name: mca_leads_management_mobile
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^3.2.2+1
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^2.0.0
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.4.0
  url_launcher: ^6.0.3
  intl: ^0.17.0
  flutter_picker: ^2.0.2
  us_states: ^1.1.5
  time_machine: ^0.9.16
  flex_color_scheme: ^4.1.1
  cached_network_image: ^3.2.0
  firebase_messaging: ^11.2.3
  basic_utils: ^3.9.3
  flutter_datetime_picker: ^1.5.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon_launcher/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon_launcher/icon.png
    - assets/launcher.jpg
    - assets/car_pic.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
